# Generated by Django 5.0.3 on 2024-04-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("share_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together=set(),
        ),
    ]
