# Generated by Django 5.0.3 on 2024-04-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("share_app", "0002_alter_location_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("city", "post_code")},
        ),
    ]
