on:
  pull_request:

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[tests]
        pip install pytest pytest-cov
    - name: Test with pytest
      run: |
        pytest tests --doctest-modules --junitxml=junit-results.xml --cov=com --cov-report=xml --cov-report=html
